version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci-deps-bump)"
    groups:
      gh-actions-deps:
        patterns:
          - "*"
