name: Bug Report
description: File a bug report (for questions, ideas & support, use the Discussions tab, or IRC for quick answers, but make sure to stay on the channel!)
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please, if you want an update on the bug report, refrain from bumping the issue. Instead, hit the 'subscribe' button on the right-hand side.

        If you want to express that you too are experiencing the same issue, please react to the original issue with a `\:+1\:` reaction.

        Additionally, please don't open 'questions' on the bug tracker. These will be turned into Discussions. To save this step, use the Discussions tab for questions, feature requests, or other things that aren't bugs.

        By following these tips, you save time for the maintainers, and avoid creating noise. Otherwise, we have to hide comments, and direct in the right direction. This would then lead to a bad user experience, and we don't want that.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see! Screenshots are also helpful - please attach to the issue (when created), rather than linking to image hosting sites.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Input Leap are you running?
      options:
        - v2.0.0-RC1
        - v2.0.0-RC2
        - v2.0.0
        - v2.1.1
        - v2.1.2
        - v2.3.0
        - v2.3.1
        - v2.3.2-alpha
        - v2.3.2
        - v2.3.3
        - v2.3.4
        - v2.4.0
        - From Git HEAD or commit (specify below)
    validations:
      required: true
  - type: input
    id: git-commit-if
    attributes:
      label: Git commit hash (if applicable)
      description: "When building Input Leap from Git, what commit hash did you checkout from?"
      placeholder: b0c0b42b
    validations:
      required: false
  - type: textarea
    id: pkg-mgr-origin
    attributes:
      label: If applicable, where did you install Input Leap from?
      description: This includes Snaps, Flatpaks, and self-built executables.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OSes are you seeing the problem on? (Check all that apply)
      multiple: true
      options:
        - Linux
        - Windows
        - macOS
        - FreeBSD
    validations:
      required: true
  - type: textarea
    id: backend
    attributes:
      label: If applicable, are you using Wayland or X11?
      description: This applies to both client(s) and the server.
    validations:
      required: false
  - type: textarea
    id: os-version
    attributes:
      label: What OS versions are you using?
      description: This applies to both client(s) and the server.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted correctly, so no need for backticks.
      render: shell
  - type: textarea
    id: misc-info
    attributes:
      label: Any other information
      description: Please enter any other information we should know, if applicable.
