if (UNIX)
    set (CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
    if (NOT CPACK_PACKAGE_VERSION)
        set(CPACK_PACKAGE_VERSION ${CMAKE_PROJECT_VERSION})
    endif()
    set (CPACK_GENERATOR "TBZ2")
    set (CPACK_SOURCE_GENERATOR "TXZ")
    set (CPACK_SOURCE_IGNORE_FILES "/build/;\.gitignore$;/\.git/;/.github/;\.swp$;build_env\.*")
    include (CPack)
endif()
